"WITH
-- 1. CTE para obtener todos los períodos relevantes para cada cliente.
--    Se usa LEFT JOIN para incluir todos los clientes de la primera tabla,
--    incluso si no tienen un RUT coincidente en la segunda.
ALL_PERIODS AS (
  SELECT
    v.RUT_HIJA AS RUTCL,
    LPAD(REGEXP_REPLACE(v.RUT_HIJA, '[\.\-]', ''), 10, '0') AS RUT_NORM,
    v.NOMBRE_AM AS AM,
    v.NOMBRE_JEFE_COMERCIAL_AM AS JC,
    v.NOMBRE_GERENTE_AREA AS SGTE,
    v.NOMBRE_GERENTE_COMERCIAL AS GTE,
    v.PERIODO
  FROM CONFORMADO_EXP.VW_PA_CARTERA_EMPRESAS v
  LEFT JOIN CONFORMADO_EXP.VW_GR_GIT_PROYECTO p
  ON LPAD(REGEXP_REPLACE(v.RUT_HIJA, '[\.\-]', ''), 10, '0') = REGEXP_REPLACE(UPPER(p.rutcliente), '[^0-9K]', '')
  WHERE v.TIPO_CARTERA = 'Cierre'
),
-- 2. CTE para aplicar la lógica de búsqueda del último valor no nulo
--    y filtrar solo el último registro por RUT.
FINAL_CART AS (
  SELECT
    RUTCL,
    RUT_NORM,
    LAST_VALUE(AM   IGNORE NULLS) OVER (PARTITION BY RUT_NORM ORDER BY PERIODO DESC) AS AM,
    LAST_VALUE(JC   IGNORE NULLS) OVER (PARTITION BY RUT_NORM ORDER BY PERIODO DESC) AS JC,
    LAST_VALUE(SGTE IGNORE NULLS) OVER (PARTITION BY RUT_NORM ORDER BY PERIODO DESC) AS SGTE,
    LAST_VALUE(GTE  IGNORE NULLS) OVER (PARTITION BY RUT_NORM ORDER BY PERIODO DESC) AS GTE,
    ROW_NUMBER() OVER (PARTITION BY RUT_NORM ORDER BY PERIODO DESC) AS RN
  FROM ALL_PERIODS
),
-- Base de proyectos
IP AS (
  SELECT
    p.*,
    REGEXP_REPLACE(TO_CHAR(p.NUMPROYECTO), '[^0-9]', '') AS NUMPROY_STR
  FROM CONFORMADO_EXP.VW_GR_GIT_PROYECTO p
  WHERE p.CODTIPOPRY IN ('APEMP','APTI')
    AND p.FOLIOPRY NOT IN ('CHI-002983389-1','CHI-002982765-1')
),
-- Bitácora de tareas normalizada
HISTO AS (
  SELECT
    g.*,
    CASE WHEN REGEXP_LIKE(TRIM(g.FLH_IDDOCUMENTO), '^[0-9]+$') THEN TRIM(g.FLH_IDDOCUMENTO) ELSE NULL END AS NUMPROY_STR
  FROM CONFORMADO_EXP.VW_GR_FLT_HISTORIA_GIT g
  WHERE g.FLH_CODFLUJO IN ('ADPEM','ADPTI')
),
-- Primer registro de creación (tarea 1)
CREACIONGIT AS (
  SELECT NUMPROY_STR, SUBSTR(FLH_FHOCREACION,1,8) AS CREACION
  FROM (
    SELECT h.NUMPROY_STR, h.FLH_FHOCREACION,
           ROW_NUMBER() OVER (PARTITION BY h.NUMPROY_STR ORDER BY h.FLH_FHOCREACION) rn
    FROM HISTO h
    WHERE h.FLH_NUMTAREA = 1
      AND h.NUMPROY_STR IS NOT NULL
  )
  WHERE rn = 1
),
-- Planificación / atrasos (redirigido a FOLIOPRY)
PLANI AS (
  SELECT
    ip.FOLIOPRY,
    MAX(p.FPA_OBSERVACION) AS FPA_OBSERVACION,
    MAX(p.FPA_DESCAUSA)    AS FPA_DESCAUSA,
    MAX(SUBSTR(REGEXP_REPLACE(TRIM(p.FPA_FHOACTUALIZACION),'[^0-9]',''),1,14)) AS FPA_FHOACTUALIZACION,
    MAX(SUBSTR(REGEXP_REPLACE(TRIM(p.FPA_FHOACTUALPLAN),'[^0-9]',''),1,14))    AS FPA_FHOACTUALPLAN,
    COUNT(DISTINCT p.FPA_FHOACTUALPLAN) AS QREP
  FROM CONFORMADO_EXP.VW_GR_FLT_PLANIFICACION_ATRASO p
  JOIN CONFORMADO_EXP.VW_GR_GIT_ITEM_PROYECTO it
    ON TRIM(p.FPA_IDDOCUMENTO) = TRIM(TO_CHAR(it.NUMITEM))
  JOIN IP ip
    ON ip.NUMPROYECTO = it.NUMPROYECTO
  GROUP BY ip.FOLIOPRY
),
-- Primer estado REPLAN
BITREP AS (
  SELECT NUMPROYECTO, REPLAN
  FROM (
    SELECT b.NUMPROYECTO, b.FHOCREACION AS REPLAN,
           ROW_NUMBER() OVER (PARTITION BY b.NUMPROYECTO ORDER BY b.FHOCREACION) rn
    FROM CONFORMADO_EXP.VW_GR_BITACORA_ESTADO_PROYECTO b
    WHERE (UPPER(NVL(b.DESESTADO,'')) LIKE '%REPLAN%' OR UPPER(NVL(b.CODESTADO,'')) LIKE '%REPLAN%')
      AND b.FHOCREACION IS NOT NULL
  )
  WHERE rn = 1
),
-- Días acumulados en 'Detenido'
DETENIDO AS (
  SELECT b.NUMPROYECTO,
         SUM( TRUNC( NVL(b.FHOTERMINO, SYSDATE) ) - TRUNC( b.FHOCREACION ) ) AS DIASACUM
  FROM CONFORMADO_EXP.VW_GR_BITACORA_ESTADO_PROYECTO b
  WHERE b.DESESTADO = 'Detenido'
  GROUP BY b.NUMPROYECTO
),
-- Última asignación/término de tarea 4
ASIGNAJP_T AS (
  SELECT NUMPROY_STR,
         MAX(FLH_FHOCREACION) KEEP (DENSE_RANK LAST ORDER BY FLH_FHOCREACION) AS ASIG_RAW,
         MAX(FLH_FHOTERMINO)  KEEP (DENSE_RANK LAST ORDER BY FLH_FHOCREACION) AS TER_RAW
  FROM HISTO
  WHERE FLH_NUMTAREA = 4
    AND NUMPROY_STR IS NOT NULL
  GROUP BY NUMPROY_STR
),
-- Primera asignación a JP (tarea 4/103)
JP_ASIGNAR AS (
  SELECT NUMPROY_STR,
         MIN(FLH_FHOCREACION) AS ASIG_RAW
  FROM HISTO
  WHERE FLH_NUMTAREA IN (4,103)
    AND NUMPROY_STR IS NOT NULL
  GROUP BY NUMPROY_STR
),
-- Jefe de Área (tarea 3)
JEFEAREA AS (
  SELECT
    NUMPROY_STR,
    MAX(FLH_FHOCREACION) KEEP (DENSE_RANK LAST ORDER BY FLH_FHOCREACION) AS FH_CRE_JA,
    MAX(FLH_NOMUSUARIO)  KEEP (DENSE_RANK LAST ORDER BY FLH_FHOCREACION) AS FLH_NOMUSUARIO,
    MAX(FLH_NUMUSUARIO)  KEEP (DENSE_RANK LAST ORDER BY FLH_FHOCREACION) AS FLH_NUMUSUARIO
  FROM HISTO
  WHERE FLH_NUMTAREA = 3
    AND TO_CHAR(FLH_NUMUSUARIO) IN ('249','132','240','68','253','930','161','1335','1048','2182','1377','2587')
    AND NUMPROY_STR IS NOT NULL
  GROUP BY NUMPROY_STR
),
-- Supervisor base (tarea 3)
SUPERVISORCO AS (
  SELECT
    NUMPROY_STR,
    MAX(FLH_NOMUSUARIO) KEEP (DENSE_RANK LAST ORDER BY FLH_FHOCREACION) AS FLH_NOMUSUARIO
  FROM HISTO
  WHERE FLH_NUMTAREA = 3
    AND NUMPROY_STR IS NOT NULL
  GROUP BY NUMPROY_STR
),
-- Supervisor alterno (tarea 142), excluye 1048
SUPERVISORCO2 AS (
  SELECT
    NUMPROY_STR,
    MAX(FLH_FHOCREACION) KEEP (DENSE_RANK LAST ORDER BY FLH_FHOCREACION) AS FH_CRE_S2,
    MAX(FLH_NOMUSUARIO)  KEEP (DENSE_RANK LAST ORDER BY FLH_FHOCREACION) AS FLH_NOMUSUARIO
  FROM HISTO
  WHERE FLH_NUMTAREA = 142
    AND TO_CHAR(FLH_NUMUSUARIO) <> '1048'
    AND NUMPROY_STR IS NOT NULL
  GROUP BY NUMPROY_STR
),
-- Marca complejidad (tarea 142)
COMPLEJO AS (
  SELECT NUMPROY_STR,
         MAX(FLH_FHOCREACION) KEEP (DENSE_RANK LAST ORDER BY FLH_FHOCREACION) AS FH_CRE_CO
  FROM HISTO
  WHERE FLH_NUMTAREA = 142
    AND NUMPROY_STR IS NOT NULL
  GROUP BY NUMPROY_STR
),
-- Último JP visto (tarea 4/103)
JP_LAST AS (
  SELECT NUMPROY_STR,
         MAX(FLH_NOMUSUARIO) KEEP (DENSE_RANK LAST ORDER BY FLH_FHOCREACION) AS FLH_NOMUSUARIO
  FROM HISTO
  WHERE FLH_NUMTAREA IN (4,103)
    AND NUMPROY_STR IS NOT NULL
  GROUP BY NUMPROY_STR
),
-- Responsable de datos (tarea 8)
JP_DATOS AS (
  SELECT NUMPROY_STR,
         MIN(FLH_NOMUSUARIO) KEEP (DENSE_RANK FIRST ORDER BY FLH_FHOCREACION) AS JPDATOS,
         MIN(FLH_FHOCREACION) AS ASIG_RAW,
         MIN(FLH_FHOTERMINO)  KEEP (DENSE_RANK FIRST ORDER BY FLH_FHOCREACION) AS TER_RAW
  FROM HISTO
  WHERE FLH_NUMTAREA = 8
    AND NUMPROY_STR IS NOT NULL
    AND FLH_FHOTERMINO NOT IN ('2012','2013','2014','2015','2016','2017','2018')
  GROUP BY NUMPROY_STR
),
-- Reglas Jefe/Supervisor
FASE1_JAREA AS (
  SELECT
    ip.NUMPROY_STR, ip.FOLIOPRY, ip.DESTECNICA,
    CASE
      WHEN UPPER(NVL(ip.NOMCLIENTE,'')) LIKE '%AGSI%' THEN 'Internacional'
      WHEN UPPER(NVL(ip.DESTECNICA,'')) LIKE '%AGSI%' THEN 'Internacional'
      WHEN ip.RUTCLIENTE IN ('0965216804','0970300007','0970300295')
           AND UPPER(NVL(ip.DESTECNICA,'')) LIKE '%ATM%' THEN 'ATM'
      ELSE
        CASE
          WHEN NVL(co.FH_CRE_CO, DATE '1900-01-01') >= NVL(ja.FH_CRE_JA, DATE '1900-01-01') THEN 'Alejandro Rifo'
          ELSE
            CASE
              WHEN ja.FLH_NUMUSUARIO IN (132) THEN 'NN-BRIC'
              WHEN ja.FLH_NUMUSUARIO IN (1335,133,161,2182,1377) THEN 'Eduardo Paredes'
              WHEN NVL(ja.FLH_NOMUSUARIO,'X') = 'Patricio Giacaman' THEN 'Luis Correa'
              WHEN UPPER(ip.DESTECNICA) LIKE '%CU %' AND UPPER(ip.DESTECNICA) LIKE '% FO%' THEN 'Alejandro Rifo'
              ELSE ja.FLH_NOMUSUARIO
            END
        END
    END AS JEFEAREA,
    CASE
      WHEN NVL(co.FH_CRE_CO, DATE '1900-01-01') >= NVL(ja.FH_CRE_JA, DATE '1900-01-01') THEN NVL(s2.FLH_NOMUSUARIO,'X')
      ELSE s1.FLH_NOMUSUARIO
    END AS SUPERVISOR,
    ip.NOMJEFEPRY AS JP,
    jd.JPDATOS,
    jd.ASIG_RAW AS ASIGNAJPDATOS_RAW,
    jd.TER_RAW  AS TERMINOJPDATOS_RAW
  FROM IP ip
  LEFT JOIN COMPLEJO      co ON co.NUMPROY_STR = ip.NUMPROY_STR
  LEFT JOIN JEFEAREA      ja ON ja.NUMPROY_STR = ip.NUMPROY_STR
  LEFT JOIN SUPERVISORCO  s1 ON s1.NUMPROY_STR = ip.NUMPROY_STR
  LEFT JOIN SUPERVISORCO2 s2 ON s2.NUMPROY_STR = ip.NUMPROY_STR
  LEFT JOIN JP_DATOS      jd ON jd.NUMPROY_STR = ip.NUMPROY_STR
),
-- Montos CHI
CHI AS (
  SELECT v.FOLIOPRY,
         NVL(v.MTOTOTALINSTVENTA,0) + NVL(v.MTOTOTALINSTRENTA,0) + NVL(v.MTOTOTALVENTA,0) AS VENTA,
         NVL(v.MTOTOTALRENTA,0) AS RENTA
  FROM CONFORMADO_EXP.VW_GR_GIT_PROYECTO v
  WHERE v.FOLIOPRY LIKE 'CHI%'
    AND TO_CHAR(v.FECESTADO,'YYYY') NOT IN ('2012','2013','2014','2015','2016','2017')
),
-- CTE para el cálculo de la fecha de creación optimizada
CREACION_OPTIMA AS (
  SELECT
    TRIM(TO_CHAR(p.NUMPROYECTO)) AS NUMPROYECTO_KEY,
    MAX(v.FLH_FHOCREACION) KEEP (DENSE_RANK FIRST ORDER BY v.FLH_FHOCREACION) AS FECHA_CREACION_RAW
  FROM CONFORMADO_EXP.VW_GR_FLT_HISTORIA_GIT v
  JOIN CONFORMADO_EXP.VW_GR_GIT_ITEM_PROYECTO i
    ON TRIM(REGEXP_REPLACE(v.FLH_IDDOCUMENTO,'[^0-9]','')) = TRIM(TO_CHAR(i.NUMITEM))
  JOIN CONFORMADO_EXP.VW_GR_GIT_PROYECTO p
    ON TRIM(TO_CHAR(i.NUMPROYECTO)) = TRIM(TO_CHAR(p.NUMPROYECTO))
  WHERE p.CODTIPOPRY IN ('APEMP','APTI')
    AND v.FLH_CODFLUJO = 'AGEPR'
    AND v.FLH_NUMTAREA = 1
    AND v.FLH_NUMTAREAPADRE = 1
  GROUP BY p.NUMPROYECTO
),
/* === CTE PARA UNIFICAR SF2 A 1 REGISTRO POR IDENTIFICADOR_OPP === */
SF2_UNICO AS (
  SELECT
    TRIM(IDENTIFICADOR_OPP) AS IDENTIFICADOR_OPP,
    MAX(DURACION_CONTRATO) AS DURACION_CONTRATO
  FROM CONFORMADO_EXP.VW_VTA_OPORTUNID_PANEL_DET_B2B
  GROUP BY TRIM(IDENTIFICADOR_OPP)
)
SELECT DISTINCT
  NVL(NULLIF(TRIM(
    CASE WHEN ip.FOLIOPRY LIKE 'CHI-%' THEN SUBSTR(ip.FOLIOPRY,1,13)
         ELSE TO_CHAR(ip.NUMOPORTUNIDAD) END
  ),''),'0') AS SISON,
  NVL(NULLIF(TRIM(ip.FOLIOPRY),''),'0') AS FolioPry,
  CASE
    WHEN REGEXP_LIKE(TRIM(TO_CHAR(ip.NUMFOLIO)), '^[0-9]+$')
      THEN TO_NUMBER(TRIM(TO_CHAR(ip.NUMFOLIO)))
    ELSE 0
  END AS Ext,
  NVL(NULLIF(TRIM(ip.RUTCLIENTE),''),'0') AS RutCl,
  NVL(NULLIF(TRIM(ip.NOMCLIENTE),''),'0') AS Cliente,
  NVL(NULLIF(TRIM(sf.SEGMENTO),''),'0') AS SEGMENTO,
  NVL(NULLIF(TRIM(ip.DESPROYECTO),''),'0') AS Proyecto,
  NVL(chi.VENTA,0) AS InstPend,
  NVL(chi.RENTA,0) AS RtaPend,
  NVL(NVL(chi.VENTA,0) + NVL(chi.RENTA,0),0) AS IRPend,
  NVL(NULLIF(TRIM(sf.DIVISA),''),'0') AS DIVISA,
  NVL(SF.FULL_CONTRACT_VALUE_NETO,0) AS FCV,
  NVL(SF.NET_ANNUAL_VALUE,0) AS NAV,
  SF2.DURACION_CONTRATO,
  /* EstadoGIT sin cambio de lógica */
  NVL(NULLIF(TRIM(
    CASE
      WHEN ip.DESESTADO = 'En Instalaciones'
       AND ( a4.TER_RAW IS NOT NULL
             AND LENGTH(a4.TER_RAW) >= 4
             AND REGEXP_LIKE(SUBSTR(a4.TER_RAW,1,4),'^[0-9]{4}$')
             AND TO_NUMBER(SUBSTR(a4.TER_RAW,1,4)) <> 1900 )
      THEN 'Terminado JP'
      ELSE ip.DESESTADO
    END
  ),''),'0') AS EstadoGIT,
  /* FecEstadoGIT → 'DD-MM-YYYY HH24:MI:SS' o default */
  COALESCE(
    CASE
      WHEN ip.FECESTADO IS NULL OR TO_CHAR(ip.FECESTADO,'DD/MM/RR') = '01/01/00'
        THEN NULL
      ELSE TO_CHAR(ip.FECESTADO, 'DD-MM-YYYY HH24:MI:SS')
    END,
    '01-01-1900 00:00:00:'
  ) AS FecEstadoGIT,
  /* Creacion desde CREACION_OPTIMA (raw 8/14/16) → formato unificado */
  COALESCE(
    CASE
      WHEN c.FECHA_CREACION_RAW IS NULL THEN NULL
      WHEN REGEXP_LIKE(TRIM(c.FECHA_CREACION_RAW), '^[0-9]{8}$')
        THEN TO_CHAR(TO_DATE(TRIM(c.FECHA_CREACION_RAW),'YYYYMMDD'),'DD-MM-YYYY HH24:MI:SS')
      WHEN REGEXP_LIKE(TRIM(c.FECHA_CREACION_RAW), '^[0-9]{14}$')
        THEN TO_CHAR(TO_DATE(TRIM(c.FECHA_CREACION_RAW),'YYYYMMDDHH24MISS'),'DD-MM-YYYY HH24:MI:SS')
      WHEN REGEXP_LIKE(TRIM(c.FECHA_CREACION_RAW), '^[0-9]{16}$')
        THEN TO_CHAR(TO_DATE(SUBSTR(TRIM(c.FECHA_CREACION_RAW),1,14),'YYYYMMDDHH24MISS'),'DD-MM-YYYY HH24:MI:SS')
      ELSE NULL
    END,
    '01-01-1900 00:00:00:'
  ) AS Creacion,
  /* FecPropuesta (DATE) → formato unificado */
  COALESCE(
    CASE
      WHEN ip.FECPROPUESTA IS NULL OR TO_CHAR(ip.FECPROPUESTA,'DD/MM/RR')='01/01/00' THEN NULL
      ELSE TO_CHAR(ip.FECPROPUESTA,'DD-MM-YYYY HH24:MI:SS')
    END,
    '01-01-1900 00:00:00:'
  ) AS FecPropuesta,
  /* FecPlanificada (DATE) → formato unificado */
  COALESCE(
    CASE
      WHEN ip.FECPLANIFICADA IS NULL OR TO_CHAR(ip.FECPLANIFICADA,'DD/MM/RR')='01/01/00' THEN NULL
      ELSE TO_CHAR(ip.FECPLANIFICADA,'DD-MM-YYYY HH24:MI:SS')
    END,
    '01-01-1900 00:00:00:'
  ) AS FecPlanificada,
  NVL(NULLIF(TRIM(red.JEFEAREA),''),'0')   AS JefeArea,
  NVL(NULLIF(TRIM(red.SUPERVISOR),''),'0') AS Supervisor,
  NVL(NULLIF(TRIM(red.JP),''),'0')         AS JP,
  /* AsignaJP (raw 8/14/16) → formato unificado */
  COALESCE(
    CASE
      WHEN a0.ASIG_RAW IS NULL THEN NULL
      WHEN REGEXP_LIKE(TRIM(a0.ASIG_RAW), '^[0-9]{8}$')
        THEN TO_CHAR(TO_DATE(TRIM(a0.ASIG_RAW), 'YYYYMMDD'), 'DD-MM-YYYY HH24:MI:SS')
      WHEN REGEXP_LIKE(TRIM(a0.ASIG_RAW), '^[0-9]{14}$')
        THEN TO_CHAR(TO_DATE(TRIM(a0.ASIG_RAW), 'YYYYMMDDHH24MISS'), 'DD-MM-YYYY HH24:MI:SS')
      WHEN REGEXP_LIKE(TRIM(a0.ASIG_RAW), '^[0-9]{16}$')
        THEN TO_CHAR(TO_DATE(SUBSTR(TRIM(a0.ASIG_RAW),1,14), 'YYYYMMDDHH24MISS'), 'DD-MM-YYYY HH24:MI:SS')
      ELSE NULL
    END,
    '01-01-1900 00:00:00:'
  ) AS AsignaJP,
  /* TerminoJP (raw 8/14/16) → formato unificado */
  COALESCE(
    CASE
      WHEN a4.TER_RAW IS NULL THEN NULL
      WHEN REGEXP_LIKE(TRIM(a4.TER_RAW), '^[0-9]{8}$')
        THEN TO_CHAR(TO_DATE(TRIM(a4.TER_RAW), 'YYYYMMDD'), 'DD-MM-YYYY HH24:MI:SS')
      WHEN REGEXP_LIKE(TRIM(a4.TER_RAW), '^[0-9]{14}$')
        THEN TO_CHAR(TO_DATE(TRIM(a4.TER_RAW), 'YYYYMMDDHH24MISS'), 'DD-MM-YYYY HH24:MI:SS')
      WHEN REGEXP_LIKE(TRIM(a4.TER_RAW), '^[0-9]{16}$')
        THEN TO_CHAR(TO_DATE(SUBSTR(TRIM(a4.TER_RAW),1,14), 'YYYYMMDDHH24MISS'), 'DD-MM-YYYY HH24:MI:SS')
      ELSE NULL
    END,
    '01-01-1900 00:00:00:'
  ) AS TerminoJP,
  NVL(NULLIF(TRIM(red.JPDATOS),''),'0') AS JpDatos,
  /* AsignaJP_Datos (raw 8/14/16) → formato unificado */
  COALESCE(
    CASE
      WHEN red.ASIGNAJPDATOS_RAW IS NULL THEN NULL
      WHEN REGEXP_LIKE(TRIM(red.ASIGNAJPDATOS_RAW), '^[0-9]{8}$')
        THEN TO_CHAR(TO_DATE(TRIM(red.ASIGNAJPDATOS_RAW), 'YYYYMMDD'), 'DD-MM-YYYY HH24:MI:SS')
      WHEN REGEXP_LIKE(TRIM(red.ASIGNAJPDATOS_RAW), '^[0-9]{14}$')
        THEN TO_CHAR(TO_DATE(TRIM(red.ASIGNAJPDATOS_RAW), 'YYYYMMDDHH24MISS'), 'DD-MM-YYYY HH24:MI:SS')
      WHEN REGEXP_LIKE(TRIM(red.ASIGNAJPDATOS_RAW), '^[0-9]{16}$')
        THEN TO_CHAR(TO_DATE(SUBSTR(TRIM(red.ASIGNAJPDATOS_RAW),1,14), 'YYYYMMDDHH24MISS'), 'DD-MM-YYYY HH24:MI:SS')
      ELSE NULL
    END,
    '01-01-1900 00:00:00:'
  ) AS AsignaJP_Datos,
  /* TerminoJP_Datos (raw 8/14/16) → formato unificado */
  COALESCE(
    CASE
      WHEN red.TERMINOJPDATOS_RAW IS NULL THEN NULL
      WHEN REGEXP_LIKE(TRIM(red.TERMINOJPDATOS_RAW), '^[0-9]{8}$')
        THEN TO_CHAR(TO_DATE(TRIM(red.TERMINOJPDATOS_RAW), 'YYYYMMDD'), 'DD-MM-YYYY HH24:MI:SS')
      WHEN REGEXP_LIKE(TRIM(red.TERMINOJPDATOS_RAW), '^[0-9]{14}$')
        THEN TO_CHAR(TO_DATE(TRIM(red.TERMINOJPDATOS_RAW), 'YYYYMMDDHH24MISS'), 'DD-MM-YYYY HH24:MI:SS')
      WHEN REGEXP_LIKE(TRIM(red.TERMINOJPDATOS_RAW), '^[0-9]{16}$')
        THEN TO_CHAR(TO_DATE(SUBSTR(TRIM(red.TERMINOJPDATOS_RAW),1,14), 'YYYYMMDDHH24MISS'), 'DD-MM-YYYY HH24:MI:SS')
      ELSE NULL
    END,
    '01-01-1900 00:00:00:'
  ) AS TerminoJP_Datos,
  /* FecActualizacion (pl.FPA_FHOACTUALIZACION raw 8/14) → formato unificado */
  COALESCE(
    CASE
      WHEN pl.FPA_FHOACTUALIZACION IS NULL THEN NULL
      WHEN LENGTH(TRIM(pl.FPA_FHOACTUALIZACION)) = 8
        THEN TO_CHAR(TO_DATE(TRIM(pl.FPA_FHOACTUALIZACION),'YYYYMMDD'),'DD-MM-YYYY HH24:MI:SS')
      WHEN LENGTH(TRIM(pl.FPA_FHOACTUALIZACION)) = 14
        THEN TO_CHAR(TO_DATE(TRIM(pl.FPA_FHOACTUALIZACION),'YYYYMMDDHH24MISS'),'DD-MM-YYYY HH24:MI:SS')
      ELSE NULL
    END,
    '01-01-1900 00:00:00:'
  ) AS FecActualizacion,
  /* PlanOriginal: prioriza plan (raw 8/14) si existe; si no, ip.FECCOMERCIAL (DATE) → formato unificado */
  COALESCE(
    CASE
      WHEN pl.FPA_FHOACTUALPLAN IS NOT NULL THEN
        CASE
          WHEN LENGTH(TRIM(pl.FPA_FHOACTUALPLAN)) = 8
            THEN TO_CHAR(TO_DATE(TRIM(pl.FPA_FHOACTUALPLAN),'YYYYMMDD'),'DD-MM-YYYY HH24:MI:SS')
          WHEN LENGTH(TRIM(pl.FPA_FHOACTUALPLAN)) = 14
            THEN TO_CHAR(TO_DATE(TRIM(pl.FPA_FHOACTUALPLAN),'YYYYMMDDHH24MISS'),'DD-MM-YYYY HH24:MI:SS')
          ELSE NULL
        END
      ELSE
        CASE
          WHEN ip.FECCOMERCIAL IS NULL OR TO_CHAR(ip.FECCOMERCIAL,'DD/MM/RR')='01/01/00' THEN NULL
          ELSE TO_CHAR(ip.FECCOMERCIAL,'DD-MM-YYYY HH24:MI:SS')
        END
    END,
    '01-01-1900 00:00:00:'
  ) AS PlanOriginal,
  NVL(NULLIF(TRIM(pl.FPA_DESCAUSA),''),'0') AS CausaReplanificacion,
  NVL(NULLIF(TRIM(pl.FPA_OBSERVACION),''),'0') AS ObsReplanificacion,
  NVL(pl.QREP,0) AS CantidadRep,
  NVL(NULLIF(TRIM(ip.TIPORESPQUIEBRE),''),'0') AS TipoQuiebre,
  NVL(NULLIF(TRIM(ip.OBSERVACIONESTADO),''),'0') AS Quiebre,
  /* FecQuiebre: ip.FHOACTUALIZACIONESTADO puede venir 8/14, NULL, '01/01/00' u otros */
  COALESCE(
    CASE
      WHEN ip.FHOACTUALIZACIONESTADO IS NULL THEN NULL
      WHEN REGEXP_LIKE(TRIM(TO_CHAR(ip.FHOACTUALIZACIONESTADO)), '^[0-9]{8}$')
        THEN TO_CHAR(TO_DATE(TRIM(TO_CHAR(ip.FHOACTUALIZACIONESTADO)),'YYYYMMDD'),'DD-MM-YYYY HH24:MI:SS')
      WHEN REGEXP_LIKE(TRIM(TO_CHAR(ip.FHOACTUALIZACIONESTADO)), '^[0-9]{14}$')
        THEN TO_CHAR(TO_DATE(TRIM(TO_CHAR(ip.FHOACTUALIZACIONESTADO)),'YYYYMMDDHH24MISS'),'DD-MM-YYYY HH24:MI:SS')
      WHEN REPLACE(TRIM(TO_CHAR(ip.FHOACTUALIZACIONESTADO)),'/','-') IN ('01-01-00','01-01-1900') THEN NULL
      ELSE TO_CHAR(CASE
                     WHEN TRUNC(ip.FHOACTUALIZACIONESTADO) = ip.FHOACTUALIZACIONESTADO
                     THEN CAST(ip.FHOACTUALIZACIONESTADO AS DATE)
                     ELSE CAST(ip.FHOACTUALIZACIONESTADO AS DATE)
                   END, 'DD-MM-YYYY HH24:MI:SS')
    END,
    '01-01-1900 00:00:00:'
  ) AS FecQuiebre,
  NVL(NULLIF(TRIM(sf.TIPOLOGIA_OPORTUNIDAD),''),'0') AS Tipologia_Oportunidad,
  NVL(NULLIF(TRIM(sf.TIPO_OPORTUNIDAD),''),'0')   AS TIPO_OPORTUNIDAD,
  NVL(NULLIF(TRIM(ip.CODCOMPLEJIDADIMPLANTACION),''),'0') AS Complejidad,
  NVL(ip.PORCAVANCE,0) AS PorcentajeReal,
  NVL(NULLIF(TRIM(fc.AM),''),'0')   AS AM,
  NVL(NULLIF(TRIM(fc.JC),''),'0')   AS JC,
  NVL(NULLIF(TRIM(fc.SGTE),''),'0') AS SGTE,
  NVL(NULLIF(TRIM(fc.GTE),''),'0')  AS GTE,
  NVL(ip.VIGENCIACONTRATO,0) AS MesPlazoFacturacion,
  NVL(det.DIASACUM,0)        AS TiempoDetenido,
  NVL(ip.NIVELMETODOLOGICO,0) AS NIVELMETODOLOGICO,
  NVL(NULLIF(TRIM(ip.DESTECNICA),''),'0') AS DESTECNICA
FROM IP ip
LEFT JOIN FASE1_JAREA red ON red.NUMPROY_STR = ip.NUMPROY_STR
LEFT JOIN CHI chi ON chi.FOLIOPRY = ip.FOLIOPRY
LEFT JOIN ASIGNAJP_T a4 ON a4.NUMPROY_STR = ip.NUMPROY_STR
LEFT JOIN JP_ASIGNAR a0 ON a0.NUMPROY_STR = ip.NUMPROY_STR
LEFT JOIN PLANI pl ON pl.FOLIOPRY = ip.FOLIOPRY
LEFT JOIN BITREP bit ON bit.NUMPROYECTO = ip.NUMPROYECTO
LEFT JOIN DETENIDO det ON det.NUMPROYECTO = ip.NUMPROYECTO
LEFT JOIN CONFORMADO_EXP.VW_INT_OPORTUNIDADES_VTAS_B2B SF ON SUBSTR(ip.FOLIOPRY, 1, 13) = SF.ID_OPORTUNIDAD_INTERNO
LEFT JOIN SF2_UNICO SF2 ON SUBSTR(ip.FOLIOPRY, 1, 13) = SF2.IDENTIFICADOR_OPP
LEFT JOIN CREACION_OPTIMA c ON c.NUMPROYECTO_KEY = TRIM(TO_CHAR(ip.NUMPROYECTO))
LEFT JOIN FINAL_CART fc ON REGEXP_REPLACE(UPPER(ip.RUTCLIENTE), '[^0-9K]', '') = fc.RUT_NORM AND fc.RN = 1
ORDER BY FolioPry"
